### ISSUE TITLE
Management key with lower case letters not accepted

### ISSUE THREAD

**Issue by bluikko** [CSIS/EnrollmentStation#11]
Some of the YubiKey tools show management keys with lower case letters. ES does not accept such management key and the letters must be changed to upper case.

The management key with lower case letters should be accepted and ES then internally convert the lower case letters to suitable case.

**Comment by Genbox** [comment]
Hi bluikko,

Thanks for reporting this issue.
We never tested the use case where the management key was generated by the yubikey tools. The ES application should of course work with the same restrictions, so this should be fixed.

**Comment by ian-csis** [comment]
Hi bluikko,

Thanks for reporting this issue.
We never tested the use case where the management key was generated by the yubikey tools. The ES application should of course work with the same restrictions, so this should be fixed.

**Comment by mike-csis** [comment]
We now accept lowercased management keys in the settings dialog. Internally we store it as a series of bytes, so we don't need internal conversion. This also means that when you see the key again, it will be uppercased.
