### ISSUE TITLE
Unable to import a certificate

### ISSUE THREAD

**Issue by bluikko** [CSIS/EnrollmentStation#13]
On enrolling a user, the error "Unable to import a certificate" is displayed. The CA has issued the certificate correctly, which I now have to revoke.

This same error happened on the first YubiKey NEO I attempted to enroll with ES. Then, I fumbled around for a few hours with this YK, tried ES again, and enrollment magically worked with ES. I was happy and moved to the next YK - again the same "Unable to import a certificate" error.

I have checked the NEO Manager, and CCID mode is enabled (disabling + re-enabling CCID did not help). PIV Manager seems to work on it.
I do not remember exactly what I did with the first YK, but it included:
- Renaming the reader with NEO Manager and resetting it back to default name
- Generate certificate with PIV Manager
- Import certificate with PIV Manager

And so on.. I specifically did NOT do any "set-ccc" / "set-chuid" / resetting on it.

**Comment by ian-csis** [comment]
I'm including the link to your post on the Yubico boards: http://forum.yubico.com/viewtopic.php?f=30&t=2412&p=8976#p8976

**Comment by bluikko** [comment]
Update:
ES enrolled certificates have 2048 bit key size. Some certificate template options were changed which likely made this particular certificate request fit on the YK NEO. The next one was likely too large and there is no bug, except that the error message is not clear. I could not import 2048 bit certificates with PIV Manager because of the YK size restriction, as seen in the board thread. In AD CS there is only "Minimum key size" setting. Certificates with 1024 bit key size fit to YK NEO consistently.

The key size should be configurable in ES.

Will try to minimize certificate size from AD CS which'll be painful. Since some crypto settings require re-installation.

**Comment by ian-csis** [comment]
That makes sense. By the way, Yubikey 4 have RSA 4096 and ECC p384 support and are MUCH faster at key generation and signing operations, which improves login times for users.

We will implement a check on key sizes to make a better error message in that particular case. I'll keep the issue open until then.

**Comment by bluikko** [comment]
May I suggest to also include RSA 1024 as one of those options. A more complex PKI will result in a larger certificate and those seem to only fit on YKs with RSA 1024 due to the ~3000 byte object maximum size limitation.
And please make the error message more descriptive!! Include the size of the too-large certificate and even the maximum size.

**Comment by gunnywong** [comment]
I'm trying to set up an enrollment station and also getting the 'unable to import a certificate, return code YKPIV_GENERIC_ERROR' I've changed the template minimum key size to 1024 and still no dice. I can use the PIV Manager to generate keys but we want to use ES with an enrollment agent.
