### ISSUE TITLE
Typo in "Enroll new SmartCard"

### ISSUE THREAD

**Issue by bluikko** [CSIS/EnrollmentStation#18]
The "Enroll new SmartCard" dialog has a typo:
"YubiHSM avaliable"
It should probable be "available" with the 'i' moved. Do you guys proof-read these at all? It reflects very poorly on the quality of the program.

![image](https://cloud.githubusercontent.com/assets/14869000/20474534/556fbe4a-aff9-11e6-8253-15f991ccc021.png)

**Comment by mike-csis** [comment]
Hi @bluikko,

Thanks for reporting this. In general I think our proofreading is good, but this one slipped through the cracks. Well spotted.

Mike.
