### ISSUE TITLE
Could you please use the "releases" functionality of GitHub?

### ISSUE THREAD

**Issue by bluikko** [CSIS/EnrollmentStation#19]
Looking at the commit frequency graph, there are clear peaks and valleys in the activity.
I do not know if it suits your development process, but could you please consider using the "releases" functionality of GitHub? This would make it much easier for end-users to get the whole thing installed. It is not very convenient to download binaries one by one.

**Comment by mike-csis** [comment]
Hi @bluikko,

I believe we already began using the Releases functionality. On the [releases](https://github.com/CSIS/EnrollmentStation/releases) page, you'll see version `0.3.4.1`. Subscribing to the releases page (possible in some feed readers) should notify you when stuff happens.

And yes - we focus our efforts on the tool when we encounter issues or need new features, hence the peaks and vallies.

Mike.
