### ISSUE TITLE
System.Threading.LockRecursionException on Enroll Yubikey

### ISSUE THREAD

**Issue by thomasDOTde** [CSIS/EnrollmentStation#2]
I've downloaded the leastest commited version and did run the complied Enrollmentstation.exe.
First I configured all required settings such as management-key, ca and agent cert.
After plugging in a yuibkey an clicking on "Enroll Yubikey" an Execution appears like this:
System.Threading.LockRecursionException: Das Einrichten von rekursiven Schreibsperren ist in diesem Modus nicht zulässig.
   bei System.Threading.ReaderWriterLockSlim.TryEnterWriteLockCore(TimeoutTracker timeout)
   bei System.Threading.ReaderWriterLockSlim.TryEnterWriteLock(TimeoutTracker timeout)
   bei EnrollmentStation.DlgEnroll.YubikeyStateChange()
   bei EnrollmentStation.DlgEnroll.DlgEnroll_Load(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)

**Comment by ian-csis** [comment]
Should be fixed in the latest version.
