### ISSUE TITLE
PUK is not displayed after being randomly generated

### ISSUE THREAD

**Issue by mcdown75** [CSIS/EnrollmentStation#21]

**Comment by mike-csis** [comment]
Hi,

The PUK is stored in the database behind the application and used for internal stuff, f.ex. when a PIN is reset.

What is your use-case for seeing the PUK code?

**Comment by mike-csis** [comment]
@mcdown75 look at the discussion in #22. I've outlined why we won't show the PUK key. You can use the same work around as bluikko to get the PUK key.

**Comment by mcdown75** [comment]
Thank you.  Sorry for the delay in response.  This is my home e-mail and it gets bombed daily with spam.
