### ISSUE TITLE
AppCrash on initialization

### ISSUE THREAD

**Issue by thomasDOTde** [CSIS/EnrollmentStation#3]
When starting the application I'm getting AppCrash Report and specific systems.
I've tried to debug and got the following Error: 
Unable to init device: YKNEOMGR_BACKEND_ERROR
   at EnrollmentStation.Code.YubikeyNeoManager..ctor()
   at EnrollmentStation.MainForm..ctor()
   at EnrollmentStation.Program.Main()

**Comment by mike-csis** [comment]
Does this happen only once, or every other run or rarely?
Has the program been able to run on the system before?
Is the system a 32-bit machine?

**Comment by ian-csis** [comment]
Should be fixed in the latest version.
