### ISSUE TITLE
Error while issuing Yubikey

### ISSUE THREAD

**Issue by truemichael** [CSIS/EnrollmentStation#33]
This issue started this AM on all enrollment stations. We're getting the attached when enrolling a Yubikey.
![enroll_error](https://user-images.githubusercontent.com/32553593/36811707-a1c52f60-1cc6-11e8-874b-6ec5e670c464.PNG)

**Comment by Genbox** [comment]
That error is from the underlying Win32 calls we make. I've seen it before if the enrollment station computer was logged into while it had no network connection. If it happens on multiple enrollment stations as you say, my guess is that the problem is with your Active Directory server.

**Comment by truemichael** [comment]
I would also think it is related to a DC except we have 6 ADDS servers and we've manually changed 3 enrollment stations to use various DCs. Also, this is only a problem on enrolling a key. Revocation and termination are functioning as expected. Updated screenshot to show where the error is presented.

**Comment by truemichael** [comment]
![enroll_error_2](https://user-images.githubusercontent.com/32553593/36813920-f447fad6-1ccd-11e8-9b71-09aa8441c1d0.PNG)

**Comment by Genbox** [comment]
Check the configuration and make sure the URL to the CA server answers correctly.

**Comment by truemichael** [comment]
Nailed it...I completely missed the CSR Endpoint. An agent changed to our old CA, which is being retired. Good catch! Thank you!
