### ISSUE TITLE
Feature Request - support for YubiKey 4 and YubiKey 4 Nano

### ISSUE THREAD

**Issue by ChrisHalos** [CSIS/EnrollmentStation#6]
Currently the Enrollment Station appears not to support the 4 and 4 Nano. If you guys need some devices to test with, please e-mail chris@yubico.com and I'd be happy to send as many as you need. Great work on this project!

**Comment by ian-csis** [comment]
Thanks a lot Chris. I will email you so that we can fix this and #7
