### ISSUE TITLE
CSIS Enrolment Station doesnt detect Key

### ISSUE THREAD

**Issue by boojew** [CSIS/EnrollmentStation#8]
I'm using a Yubikey4 w/ OTP and CSIS turned on, and Enrollment Station does not detect it. Windows sees it a smart card reader.

**Comment by mike-csis** [comment]
Is this issue still present?

**Comment by boojew** [comment]
Yes

**Comment by mike-csis** [comment]
Hi, sorry for the late reply. This must have gotten lost in a vacation :/.

 Can you use the Yubico PIV tool to see if you can detect it?
The commands I'm f.ex. looking for is:

`yubico-piv-tool.exe -a status`

If the Yubico PIV tool can detect it, something is definitely wrong - as we use the same backing library.

The PIV tool: https://developers.yubico.com/yubico-piv-tool/
Download page: https://developers.yubico.com/yubico-piv-tool/Releases/
